# config.example.nim
#
# This file is not included by the current source or build scripts.
# Build inputs are generated by build.ps1, build_sentinel.ps1, and the
# hardened builders. Keep deployment secrets in environment variables or
# generated, gitignored include files.

const
  CFG_AGENT_SECRET* = ""
  CFG_WEB_USER* = ""
  CFG_WEB_PASS* = ""
  CFG_TG_BOT_TOKEN* = ""
  CFG_TG_CHAT_ID* = ""
  CFG_C2_URLS* = @["ws://127.0.0.1:8443"]
  CFG_PINNED_CERT_PEM* = ""
  CFG_BUILD_PREFIX* = "X7K"
